// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_Avancerad_.NET.Models;

namespace Projekt_Avancerad_.NET.Migrations
{
    [DbContext(typeof(ProgramDbContext))]
    partial class ProgramDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FName = "Erik",
                            LName = "Norell",
                            Title = "Utvecklare"
                        },
                        new
                        {
                            Id = 2,
                            FName = "Viktor",
                            LName = "Gunnarsson",
                            Title = "Utvecklare"
                        },
                        new
                        {
                            Id = 3,
                            FName = "Lukas",
                            LName = "Rose",
                            Title = "Utvecklare"
                        },
                        new
                        {
                            Id = 4,
                            FName = "Erik",
                            LName = "Risholm",
                            Title = "Utvecklare"
                        });
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectName = "Lion Bank"
                        },
                        new
                        {
                            Id = 2,
                            ProjectName = "Numbers Game"
                        },
                        new
                        {
                            Id = 3,
                            ProjectName = "Car Race application"
                        });
                });

            modelBuilder.Entity("Models.TimeReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("HoursWorked")
                        .HasColumnType("float");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetId")
                        .HasColumnType("int");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TimeReports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            HoursWorked = 5.0,
                            ProjetId = 1,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 1,
                            HoursWorked = 10.0,
                            ProjetId = 2,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 2,
                            HoursWorked = 2.0,
                            ProjetId = 1,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 2,
                            HoursWorked = 15.0,
                            ProjetId = 3,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 3,
                            HoursWorked = 7.0,
                            ProjetId = 2,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = 3,
                            HoursWorked = 7.0,
                            ProjetId = 3,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 7,
                            EmployeeId = 4,
                            HoursWorked = 1.0,
                            ProjetId = 1,
                            WeekNumber = 12
                        },
                        new
                        {
                            Id = 8,
                            EmployeeId = 4,
                            HoursWorked = 20.0,
                            ProjetId = 3,
                            WeekNumber = 12
                        });
                });

            modelBuilder.Entity("Models.TimeReport", b =>
                {
                    b.HasOne("Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });
#pragma warning restore 612, 618
        }
    }
}
